# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: auth.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
import auth_pb2


class AuthenticationBase(abc.ABC):

    @abc.abstractmethod
    async def GetCurrentUser(self, stream: 'grpclib.server.Stream[auth_pb2.UserRequest, auth_pb2.User]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/auth.Authentication/GetCurrentUser': grpclib.const.Handler(
                self.GetCurrentUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                auth_pb2.UserRequest,
                auth_pb2.User,
            ),
        }


class AuthenticationStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetCurrentUser = grpclib.client.UnaryUnaryMethod(
            channel,
            '/auth.Authentication/GetCurrentUser',
            auth_pb2.UserRequest,
            auth_pb2.User,
        )
