import { Metadata } from "next";
import ClientLayout from "@/components/client-layout";
import "./globals.css";
import "katex/dist/katex.min.css";

export const metadata: Metadata = {
  title: "edux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans font-light" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ClientLayout> {children} </ClientLayout>
      </body>
    </html>
  );
}