# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\nAllCourses\x12\'\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x16.course.CourseInstance\"\xcf\x01\n\x0e\x43ourseInstance\x12\x11\n\tcourse_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x1a\n\x12\x63ourse_description\x18\x03 \x01(\t\x12\x13\n\x0b\x63ourse_code\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x03\x12\x1b\n\x13\x63ourse_syllabus_url\x18\x06 \x01(\t\x12\x1d\n\x15\x63ourse_study_plan_url\x18\x07 \x01(\t\x12\x17\n\x0f\x63ourse_icon_url\x18\x08 \x01(\t\"&\n\x13\x41llCoursesDBRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x32J\n\x06\x43ourse\x12@\n\rGetAllCourses\x12\x1b.course.AllCoursesDBRequest\x1a\x12.course.AllCoursesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLCOURSES']._serialized_start=57
  _globals['_ALLCOURSES']._serialized_end=110
  _globals['_COURSEINSTANCE']._serialized_start=113
  _globals['_COURSEINSTANCE']._serialized_end=320
  _globals['_ALLCOURSESDBREQUEST']._serialized_start=322
  _globals['_ALLCOURSESDBREQUEST']._serialized_end=360
  _globals['_COURSE']._serialized_start=362
  _globals['_COURSE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
