# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: course.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
from . import course_pb2


class CourseBase(abc.ABC):

    @abc.abstractmethod
    async def GetAllCourses(self, stream: 'grpclib.server.Stream[course_pb2.AllCoursesDBRequest, course_pb2.AllCourses]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/course.Course/GetAllCourses': grpclib.const.Handler(
                self.GetAllCourses,
                grpclib.const.Cardinality.UNARY_UNARY,
                course_pb2.AllCoursesDBRequest,
                course_pb2.AllCourses,
            ),
        }


class CourseStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetAllCourses = grpclib.client.UnaryUnaryMethod(
            channel,
            '/course.Course/GetAllCourses',
            course_pb2.AllCoursesDBRequest,
            course_pb2.AllCourses,
        )
